name: release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test

      - name: Build artifacts
        run: pnpm run build

      - name: Upload assets to GitHub
        uses: AButler/upload-release-assets@v2.0
        with:
          files: "dist/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
